name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0

      - name: Fetch NPM dependencies
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          export PATH=$HOME/.npm-global/bin:$PATH
          npm install -g @babel/cli @babel/core
          yarn

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true

      - uses: actions/checkout@v2
        name: Checkout Site
        with:
          repository: 'lipukule/lipukule.github.io'
          submodules: false
          fetch-depth: 0
          path: './public/'

      - name: Build Site
        run: |
          cd public
          git rm -rf . || true
          cd ..
          hugo --minify
          cd public
          git config --local --unset-all "http.https://github.com/.extraheader"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Deploy site" --allow-empty

      - name: Deploy Site
        uses: ad-m/github-push-action@master
        with:
          repository: 'lipukule/lipukule.github.io'
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
          directory: './public/'
          force: true
